version: '3'
services:
  overflow:
    image: huild/overflow-docker:latest
    container_name: overflow
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./plugins:/overflow/plugins
      - ./config:/overflow/config
      - ./bots:/overflow/bots
      - ./logs:/overflow/logs
      - ./data:/overflow/data
      - ./overflow.json:/overflow/overflow.json
    network_mode: bridge
