name: Build and Release Docker Image

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Latest Release Version
      id: get-latest-version
      run: |
        latest_release=$(curl -s https://api.github.com/repos/MrXiaoM/Overflow/releases/latest | jq -r .tag_name)
        echo "Latest release version: $latest_release"
        echo "latest_version=$latest_release" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" registry.cn-hangzhou.aliyuncs.com
        docker build -t registry.cn-hangzhou.aliyuncs.com/starfishes/overflow-docker:${{ env.latest_version }} . 
        docker tag registry.cn-hangzhou.aliyuncs.com/starfishes/overflow-docker:${{ env.latest_version }} registry.cn-hangzhou.aliyuncs.com/starfishes/overflow-docker:latest
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/overflow-docker:${{ env.latest_version }}
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/overflow-docker:latest