name: Auto Build Overflow

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 1 * *'  # 每天 UTC 时间 3 点自动构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest version
      id: version
      run: |
        METADATA_URL="https://repo.maven.apache.org/maven2/top/mrxiaom/mirai/overflow-core-all/maven-metadata.xml"
        LATEST=$(curl -s $METADATA_URL | grep -oP '<latest>\K[^<]+')
        echo "version=${LATEST}" >> $GITHUB_ENV

    - name: Log in to Alibaba Cloud Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}  # Set these in your GitHub Secrets
        password: ${{ secrets.REGISTRY_PASSWORD }}  # Set these in your GitHub Secrets

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile 
        build-args: |
          OVERFLOW_VERSION=${{ env.version }}
        tags: |
          pocketfan233/overflow-docker:latest
          pocketfan233/overflow-docker:${{ env.version }}
        push: true
      env:
        DOCKER_BUILDKIT: 1
  
